services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports: 
      - 10002:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - sail